export const arrayOfCategory = [
  "aerobatics",
  "anatomy",
  "biology",
  "chemistry",
  "economics",
  "engineering",
  "mathematics",
  "medicine",
  "nursing",
  "philosophy",
  "physics",
  "religion",
  "sociology",
  "science",
  "zoology",
];
